# docker-compose.yml

version: "3.9"

services:
  shakadb:
    container_name: shakadb
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - .:/app

  mysql:
    image: mysql:8.3
    container_name: shakadb_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
