# docker-compose.yml
services:
  shakadb:
    env_file:
    - .env.docker
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://johndoe:ShAkA1234%25%40@mysql:3306/shaka
    command: sh -c "npm run prisma:db:push && npm run prisma:db:seed && echo 'Done' && sleep 1"

  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
